[SERVER]
host = 103.175.217.23
port = 9090

[LOCATION]
name = perseroda

[NETWORK]

; kualitas JPEG 1-100
jpeg_quality = 45

; lebar maksimum video
max_width = 800

; frame per detik
fps = 5


[CAMERA_5]
name = Pintu Depan
rtsp = rtsp://admin:admin@192.168.8.105:554/Streaming/Channels/101

[CAMERA_6]
name = Pintu Keluar
rtsp = rtsp://admin:admin@192.168.8.102:554/Streaming/Channels/101

[CAMERA_7]
name = Pintu Keluar mtr
rtsp = rtsp://admin:admin@192.168.8.104:554/Streaming/Channels/101
